### ISSUE TITLE
fetch-factory's promise doesn't reject

### ISSUE THREAD

**Issue by vischlatter** [jackfranklin/fetch-factory#25]
Right now the promise always resolves. I realised it while I was trying to fix the failing test. I wanted to catch the error with the catch method. As the promise never rejects the catch method is never called.

As a user of this lib I would assume that the promise rejects according to the specification.

I could try to fix this, just say the word. ;-)

**Comment by jackfranklin** [comment]
It should do, as per https://github.com/jackfranklin/fetch-factory/blob/master/src/index.js#L63, which includes the `throwsOnBadResponse` error. That's odd. Happy if you'd like to dip in and try to figure it out!

If you do, feel free to do it as part of #24 so we can merge one PR with all tests green :)

**Comment by vischlatter** [comment]
Ok, I will give it a try. 

The problem is the promise itself: https://github.com/jackfranklin/fetch-factory/blob/master/src/index.js#L86

By calling the resolve method by default, the promise doesn't reject. That's why I cannot use the Promise.protoype.catch method for error handling.

I found a very good SO-Thread about this: http://stackoverflow.com/questions/17293546/when-to-reject-resolve-a-promise

I think fetch-factory should handle everything else than a 2xx status by rejecting the promise. My opinion, I'm open to others. Would make error handling a lot easier, though. ;-)

**Comment by jackfranklin** [comment]
OK - I still think that `Promise.resolve` shouldn't be an issue but it's late and I'm not in the best state to look at the code! If the test is failing on your PR then I'll pull that down and have a look :)
